project_id = "qsjnjitjbegtrxgwqygg"

[functions.calculate-shipping]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.recommend-plants]
verify_jwt = false

[functions.api-catalog]
verify_jwt = false

[functions.api-analytics]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
